"""Retrieval public API."""

from rag_core.retrieval.errors import (
    RetrievalError,
    RetrievalErrorCode,
    RetrievalStage,
)
from rag_core.retrieval.fusion import (
    RRFContribution,
    RRFCandidate,
    RRFDiagnostics,
    RRFResult,
    RankedCandidate,
    RankedRoute,
    RouteStatus,
    dense_ranked_route,
    failed_ranked_route,
    lexical_ranked_route,
    reciprocal_rank_fusion,
)
from rag_core.retrieval.hybrid import (
    FinalSelectionDecision,
    FixedHybridRetriever,
    HybridRetrieverConfig,
    NoResultReason,
    RetrievalReport,
    RetrievalResult,
    RouteControlReport,
    ThresholdDecision,
    ThresholdStatus,
)
from rag_core.retrieval.models import (
    ChunkIndexReport,
    DenseDiagnostics,
    DenseHit,
    DenseSearchMode,
    DenseSearchResult,
    DeleteReport,
    LexicalDiagnostics,
    LexicalHit,
    LexicalIndexReport,
    LexicalSearchResult,
)
from rag_core.retrieval.postgres_chunks import PostgresChunkStore
from rag_core.retrieval.postgres_dense import PostgresDenseRetriever
from rag_core.retrieval.postgres_fts import PostgresFTSRetriever

__all__ = [
    "ChunkIndexReport",
    "DenseDiagnostics",
    "DenseHit",
    "DenseSearchMode",
    "DenseSearchResult",
    "DeleteReport",
    "FinalSelectionDecision",
    "FixedHybridRetriever",
    "HybridRetrieverConfig",
    "LexicalDiagnostics",
    "LexicalHit",
    "LexicalIndexReport",
    "LexicalSearchResult",
    "NoResultReason",
    "PostgresChunkStore",
    "PostgresDenseRetriever",
    "PostgresFTSRetriever",
    "RRFContribution",
    "RRFCandidate",
    "RRFDiagnostics",
    "RRFResult",
    "RankedCandidate",
    "RankedRoute",
    "RetrievalError",
    "RetrievalErrorCode",
    "RetrievalReport",
    "RetrievalResult",
    "RetrievalStage",
    "RouteControlReport",
    "RouteStatus",
    "ThresholdDecision",
    "ThresholdStatus",
    "dense_ranked_route",
    "failed_ranked_route",
    "lexical_ranked_route",
    "reciprocal_rank_fusion",
]
