"""Shared RAG capabilities for the review assistant."""

from rag_core.chunking import (
    Chunk,
    ChunkKind,
    ChunkPolicy,
    ChunkReport,
    ChunkResult,
    ChunkSourceSpan,
    ChunkStrategy,
    chunk_document,
)
from rag_core.ingestion import (
    DocumentElement,
    ElementKind,
    EvidenceEligibility,
    FileArtifact,
    FileFormat,
    IngestionError,
    IngestionErrorCode,
    IngestionStage,
    KnowledgeDocument,
    LoadReport,
    LoadResult,
    LoadWarning,
    LoaderConfig,
    SourceLocator,
    SourceRole,
    load_document,
)

__all__ = [
    "Chunk",
    "ChunkKind",
    "ChunkPolicy",
    "ChunkReport",
    "ChunkResult",
    "ChunkSourceSpan",
    "ChunkStrategy",
    "DocumentElement",
    "ElementKind",
    "EvidenceEligibility",
    "FileArtifact",
    "FileFormat",
    "IngestionError",
    "IngestionErrorCode",
    "IngestionStage",
    "KnowledgeDocument",
    "LoadReport",
    "LoadResult",
    "LoadWarning",
    "LoaderConfig",
    "SourceLocator",
    "SourceRole",
    "chunk_document",
    "load_document",
]
